auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: XIAO HU
url: https://huxiao64.github.io/
feed: /atom.xml
author_info: <a href="http://huxiao64.github.io/">Wei Li</a>
